export const library = {
  greek: {
    id: "greek",
    language: "古希腊语",
    shortLanguage: "希腊语",
    lang: "grc",
    direction: "ltr",
    author: "Ὅμηρος · 荷马",
    title: "Ἰλιάς",
    titleZh: "《伊利亚特》",
    edition: "Homeri Ilias, OCT",
    passage: "第一卷 · 1–7 行",
    progress: 12,
    coverMark: "Ι",
    chapters: [
      { label: "第一卷", detail: "瘟疫与愤怒", active: true },
      { label: "第二卷", detail: "梦与船表", active: false },
      { label: "第三卷", detail: "墙头点将", active: false },
      { label: "第四卷", detail: "盟约破裂", active: false },
      { label: "第五卷", detail: "狄俄墨得斯", active: false },
      { label: "第六卷", detail: "赫克托耳归城", active: false },
    ],
    sections: ["1–7", "8–16", "17–32", "33–42", "43–52", "53–67"],
    lines: [
      {
        n: "1",
        translation: "女神啊，请歌唱佩琉斯之子阿基琉斯的愤怒——",
        tokens: [
          { id: "g1", form: "Μῆνιν", lemma: "μῆνις", reading: "mê-nin", pos: "名词", morphology: ["阴性", "单数", "宾格"], gloss: "愤怒；神圣的震怒", role: "宾语", relation: "唱诵的内容", confidence: 98 },
          { id: "g2", form: "ἄειδε", lemma: "ἀείδω", reading: "á-ei-de", pos: "动词", morphology: ["现在时", "主动", "命令式", "第二人称单数"], gloss: "歌唱，吟诵", role: "谓语", relation: "全句核心", confidence: 99 },
          { id: "g3", form: "θεὰ", lemma: "θεά", reading: "the-á", pos: "名词", morphology: ["阴性", "单数", "呼格"], gloss: "女神", role: "呼语", relation: "被祈求者", confidence: 99 },
          { id: "g4", form: "Πηληϊάδεω", lemma: "Πηληϊάδης", reading: "Pē-lē-i-á-deō", pos: "专有名词", morphology: ["阳性", "单数", "属格"], gloss: "佩琉斯之子", role: "定语", relation: "修饰 Ἀχιλῆος", confidence: 97 },
          { id: "g5", form: "Ἀχιλῆος", lemma: "Ἀχιλλεύς", reading: "A-khi-lê-os", pos: "专有名词", morphology: ["阳性", "单数", "属格"], gloss: "阿基琉斯", role: "定语", relation: "修饰 μῆνιν", confidence: 99 },
        ],
      },
      {
        n: "2",
        translation: "那毁灭性的愤怒，给阿开奥斯人带来无数苦难，",
        tokens: [
          { id: "g6", form: "οὐλομένην", lemma: "οὐλόμενος", reading: "ou-lo-mé-nēn", pos: "形容词", morphology: ["阴性", "单数", "宾格"], gloss: "毁灭性的，可憎的", role: "定语", relation: "修饰 μῆνιν", confidence: 96 },
          { id: "g7", form: "ἣ", lemma: "ὅς", reading: "hē", pos: "关系代词", morphology: ["阴性", "单数", "主格"], gloss: "它；那一个", role: "主语", relation: "指代 μῆνιν", confidence: 99 },
          { id: "g8", form: "μυρί᾽", lemma: "μυρίος", reading: "my-rí-a", pos: "形容词", morphology: ["中性", "复数", "宾格"], gloss: "无数的", role: "定语", relation: "修饰 ἄλγεα", confidence: 96 },
          { id: "g9", form: "Ἀχαιοῖς", lemma: "Ἀχαιός", reading: "A-khai-oîs", pos: "名词", morphology: ["阳性", "复数", "与格"], gloss: "阿开奥斯人，希腊人", role: "间接宾语", relation: "承受苦难者", confidence: 99 },
          { id: "g10", form: "ἄλγε᾽", lemma: "ἄλγος", reading: "ál-ge-a", pos: "名词", morphology: ["中性", "复数", "宾格"], gloss: "痛苦，灾难", role: "宾语", relation: "ἔθηκε 的宾语", confidence: 97 },
          { id: "g11", form: "ἔθηκε", lemma: "τίθημι", reading: "é-thē-ke", pos: "动词", morphology: ["不定过去时", "主动", "直陈式", "第三人称单数"], gloss: "造成，置于", role: "谓语", relation: "关系从句核心", confidence: 99 },
        ],
      },
      {
        n: "3",
        translation: "把许多英雄的强健灵魂抛入哈得斯，",
        tokens: [
          { id: "g12", form: "πολλὰς", lemma: "πολύς", reading: "pol-lás", pos: "形容词", morphology: ["阴性", "复数", "宾格"], gloss: "许多", role: "定语", relation: "修饰 ψυχὰς", confidence: 99 },
          { id: "g13", form: "δ᾽", lemma: "δέ", reading: "de", pos: "小品词", morphology: ["后置连接"], gloss: "而；又", role: "连接", relation: "衔接上下文", confidence: 99 },
          { id: "g14", form: "ἰφθίμους", lemma: "ἴφθιμος", reading: "iph-thí-mous", pos: "形容词", morphology: ["阴性", "复数", "宾格"], gloss: "强健的，英勇的", role: "定语", relation: "修饰 ψυχὰς", confidence: 96 },
          { id: "g15", form: "ψυχὰς", lemma: "ψυχή", reading: "psy-khás", pos: "名词", morphology: ["阴性", "复数", "宾格"], gloss: "灵魂，生命", role: "宾语", relation: "προΐαψεν 的宾语", confidence: 99 },
          { id: "g16", form: "Ἄϊδι", lemma: "Ἅιδης", reading: "Há-i-di", pos: "专有名词", morphology: ["阳性", "单数", "与格"], gloss: "哈得斯；冥府", role: "间接宾语", relation: "灵魂的去处", confidence: 98 },
          { id: "g17", form: "προΐαψεν", lemma: "προϊάπτω", reading: "pro-í-ap-sen", pos: "动词", morphology: ["不定过去时", "主动", "直陈式", "第三人称单数"], gloss: "投掷，送往", role: "谓语", relation: "主句核心", confidence: 97 },
        ],
      },
      {
        n: "4",
        translation: "又把英雄本身变成狗和百鸟的猎物；",
        tokens: [
          { id: "g18", form: "ἡρώων", lemma: "ἥρως", reading: "hē-rṓ-ōn", pos: "名词", morphology: ["阳性", "复数", "属格"], gloss: "英雄们", role: "定语", relation: "修饰 ψυχὰς", confidence: 97 },
          { id: "g19", form: "αὐτοὺς", lemma: "αὐτός", reading: "au-toús", pos: "代词", morphology: ["阳性", "复数", "宾格"], gloss: "他们自身", role: "宾语", relation: "指英雄的躯体", confidence: 99 },
          { id: "g20", form: "δὲ", lemma: "δέ", reading: "dé", pos: "小品词", morphology: ["后置连接"], gloss: "而；又", role: "连接", relation: "转折推进", confidence: 99 },
          { id: "g21", form: "ἑλώρια", lemma: "ἑλώριον", reading: "he-lṓ-ri-a", pos: "名词", morphology: ["中性", "复数", "宾格"], gloss: "猎物，战利品", role: "表语", relation: "与 τεῦχε 构成宾补", confidence: 96 },
          { id: "g22", form: "τεῦχε", lemma: "τεύχω", reading: "teû-khe", pos: "动词", morphology: ["未完成过去时", "主动", "直陈式", "第三人称单数"], gloss: "使成为，制作", role: "谓语", relation: "主句核心", confidence: 96 },
          { id: "g23", form: "κύνεσσιν", lemma: "κύων", reading: "ký-nes-sin", pos: "名词", morphology: ["阳性", "复数", "与格"], gloss: "狗", role: "间接宾语", relation: "猎物的食者", confidence: 98 },
        ],
      },
      {
        n: "5",
        translation: "宙斯的意志就这样实现了。",
        tokens: [
          { id: "g24", form: "οἰωνοῖσί", lemma: "οἰωνός", reading: "oi-ō-noî-sí", pos: "名词", morphology: ["阳性", "复数", "与格"], gloss: "猛禽，鸟类", role: "间接宾语", relation: "与 κύνεσσιν 并列", confidence: 96 },
          { id: "g25", form: "τε", lemma: "τε", reading: "te", pos: "小品词", morphology: ["后置连接"], gloss: "和", role: "连接", relation: "连接名词短语", confidence: 99 },
          { id: "g26", form: "πᾶσι", lemma: "πᾶς", reading: "pâ-si", pos: "形容词", morphology: ["阳性", "复数", "与格"], gloss: "所有", role: "定语", relation: "修饰鸟类", confidence: 98 },
          { id: "g27", form: "Διὸς", lemma: "Ζεύς", reading: "Di-òs", pos: "专有名词", morphology: ["阳性", "单数", "属格"], gloss: "宙斯的", role: "定语", relation: "修饰 βουλή", confidence: 99 },
          { id: "g28", form: "δ᾽", lemma: "δέ", reading: "de", pos: "小品词", morphology: ["后置连接"], gloss: "而", role: "连接", relation: "衔接总结", confidence: 99 },
          { id: "g29", form: "ἐτελείετο", lemma: "τελέω", reading: "e-te-leí-e-to", pos: "动词", morphology: ["未完成过去时", "中间/被动", "直陈式", "第三人称单数"], gloss: "实现，完成", role: "谓语", relation: "句子核心", confidence: 96 },
          { id: "g30", form: "βουλή", lemma: "βουλή", reading: "bou-lḗ", pos: "名词", morphology: ["阴性", "单数", "主格"], gloss: "意志，谋划", role: "主语", relation: "被实现之事", confidence: 99 },
        ],
      },
      {
        n: "6–7",
        translation: "请从最初唱起：阿特柔斯之子、众人之王，如何与神样的阿基琉斯发生争执。",
        tokens: [
          { id: "g31", form: "ἐξ", lemma: "ἐκ", reading: "ex", pos: "介词", morphology: ["支配属格"], gloss: "从，由", role: "介词", relation: "引导起点", confidence: 99 },
          { id: "g32", form: "οὗ", lemma: "ὅς", reading: "hoû", pos: "关系代词", morphology: ["中性", "单数", "属格"], gloss: "从何处", role: "宾语", relation: "与 ἐξ 构成短语", confidence: 98 },
          { id: "g33", form: "δὴ", lemma: "δή", reading: "dḕ", pos: "小品词", morphology: ["强调"], gloss: "正是；那么", role: "语气", relation: "强调叙事起点", confidence: 97 },
          { id: "g34", form: "τὰ", lemma: "ὁ", reading: "tà", pos: "冠词", morphology: ["中性", "复数", "主格"], gloss: "这些事", role: "主语", relation: "指代争执", confidence: 98 },
          { id: "g35", form: "πρῶτα", lemma: "πρῶτος", reading: "prô-ta", pos: "副词", morphology: ["最高级"], gloss: "最初，首先", role: "状语", relation: "修饰 ξυνέστην", confidence: 99 },
          { id: "g36", form: "διαστήτην", lemma: "διΐστημι", reading: "di-a-stḗ-tēn", pos: "动词", morphology: ["不定过去时", "主动", "双数", "第三人称"], gloss: "两人分裂，争执", role: "谓语", relation: "主句核心", confidence: 94 },
          { id: "g37", form: "ἐρίσαντε", lemma: "ἐρίζω", reading: "e-rí-san-te", pos: "分词", morphology: ["不定过去时", "主动", "阳性双数", "主格"], gloss: "两人争吵之后", role: "状语", relation: "说明分裂原因", confidence: 95 },
          { id: "g38", form: "Ἀτρεΐδης", lemma: "Ἀτρεΐδης", reading: "A-tre-í-dēs", pos: "专有名词", morphology: ["阳性", "单数", "主格"], gloss: "阿特柔斯之子", role: "主语", relation: "与 Ἀχιλλεύς 并列", confidence: 99 },
          { id: "g39", form: "τε", lemma: "τε", reading: "te", pos: "小品词", morphology: ["连接"], gloss: "与", role: "连接", relation: "并列两个人名", confidence: 99 },
          { id: "g40", form: "ἄναξ", lemma: "ἄναξ", reading: "á-nax", pos: "名词", morphology: ["阳性", "单数", "主格"], gloss: "君王，领袖", role: "同位语", relation: "说明阿特柔斯之子", confidence: 98 },
          { id: "g41", form: "ἀνδρῶν", lemma: "ἀνήρ", reading: "an-drôn", pos: "名词", morphology: ["阳性", "复数", "属格"], gloss: "人们，战士们", role: "定语", relation: "修饰 ἄναξ", confidence: 99 },
          { id: "g42", form: "καὶ", lemma: "καί", reading: "kaì", pos: "连词", morphology: ["并列"], gloss: "和", role: "连接", relation: "并列主语", confidence: 99 },
          { id: "g43", form: "δῖος", lemma: "δῖος", reading: "dî-os", pos: "形容词", morphology: ["阳性", "单数", "主格"], gloss: "神一样的，高贵的", role: "定语", relation: "修饰 Ἀχιλλεύς", confidence: 97 },
          { id: "g44", form: "Ἀχιλλεύς", lemma: "Ἀχιλλεύς", reading: "A-khil-leús", pos: "专有名词", morphology: ["阳性", "单数", "主格"], gloss: "阿基琉斯", role: "主语", relation: "并列主语", confidence: 99 },
        ],
      },
    ],
  },
  latin: {
    id: "latin",
    language: "拉丁语",
    shortLanguage: "拉丁语",
    lang: "la",
    direction: "ltr",
    author: "Vergilius · 维吉尔",
    title: "Aeneis",
    titleZh: "《埃涅阿斯纪》",
    edition: "P. Vergili Maronis Opera",
    passage: "第一卷 · 1–7 行",
    progress: 8,
    coverMark: "Æ",
    chapters: [
      { label: "第一卷", detail: "风暴与迦太基", active: true },
      { label: "第二卷", detail: "特洛伊陷落", active: false },
      { label: "第三卷", detail: "海上漂泊", active: false },
      { label: "第四卷", detail: "狄多女王", active: false },
      { label: "第五卷", detail: "西西里竞赛", active: false },
      { label: "第六卷", detail: "冥府之行", active: false },
    ],
    sections: ["1–7", "8–22", "23–33", "34–49", "50–80", "81–101"],
    lines: [
      {
        n: "1",
        translation: "我歌唱武器和那位英雄；他最初从特洛伊海岸，",
        tokens: [
          { id: "l1", form: "Arma", lemma: "arma", reading: "ar-ma", pos: "名词", morphology: ["中性", "复数", "宾格"], gloss: "武器；战争", role: "宾语", relation: "cano 的宾语", confidence: 99 },
          { id: "l2", form: "virumque", lemma: "vir + -que", reading: "wi-rum-kwe", pos: "名词 + 连词", morphology: ["阳性", "单数", "宾格"], gloss: "以及那位英雄", role: "宾语", relation: "与 arma 并列", confidence: 99 },
          { id: "l3", form: "cano", lemma: "canō", reading: "ka-nō", pos: "动词", morphology: ["现在时", "主动", "直陈式", "第一人称单数"], gloss: "我歌唱", role: "谓语", relation: "全句核心", confidence: 99 },
          { id: "l4", form: "Troiae", lemma: "Trōia", reading: "troi-ae", pos: "专有名词", morphology: ["阴性", "单数", "属格"], gloss: "特洛伊的", role: "定语", relation: "修饰 oris", confidence: 98 },
          { id: "l5", form: "qui", lemma: "quī", reading: "kwī", pos: "关系代词", morphology: ["阳性", "单数", "主格"], gloss: "他；那个人", role: "主语", relation: "指代 virum", confidence: 99 },
          { id: "l6", form: "primus", lemma: "prīmus", reading: "prī-mus", pos: "形容词", morphology: ["阳性", "单数", "主格"], gloss: "最先的，最初", role: "表语", relation: "修饰 qui", confidence: 98 },
          { id: "l7", form: "ab", lemma: "ab", reading: "ab", pos: "介词", morphology: ["支配夺格"], gloss: "从", role: "介词", relation: "引导出发地", confidence: 99 },
          { id: "l8", form: "oris", lemma: "ōra", reading: "ō-ris", pos: "名词", morphology: ["阴性", "复数", "夺格"], gloss: "海岸", role: "介词宾语", relation: "与 ab 构成短语", confidence: 97 },
        ],
      },
      {
        n: "2",
        translation: "被命运驱逐，来到意大利和拉维尼亚海岸，",
        tokens: [
          { id: "l9", form: "Italiam", lemma: "Italia", reading: "i-ta-li-am", pos: "专有名词", morphology: ["阴性", "单数", "宾格"], gloss: "意大利", role: "方向宾语", relation: "表示目的地", confidence: 99 },
          { id: "l10", form: "fato", lemma: "fātum", reading: "fā-tō", pos: "名词", morphology: ["中性", "单数", "夺格"], gloss: "命运", role: "状语", relation: "原因/施事", confidence: 98 },
          { id: "l11", form: "profugus", lemma: "profugus", reading: "pro-fu-gus", pos: "形容词", morphology: ["阳性", "单数", "主格"], gloss: "流亡的，被放逐的", role: "表语", relation: "说明英雄状态", confidence: 99 },
          { id: "l12", form: "Laviniaque", lemma: "Lavīnia + -que", reading: "la-wi-ni-a-kwe", pos: "专有名词 + 连词", morphology: ["中性", "复数", "宾格"], gloss: "以及拉维尼亚的", role: "定语", relation: "修饰 litora", confidence: 96 },
          { id: "l13", form: "venit", lemma: "veniō", reading: "we-nit", pos: "动词", morphology: ["完成时", "主动", "直陈式", "第三人称单数"], gloss: "来到", role: "谓语", relation: "关系从句核心", confidence: 96 },
          { id: "l14", form: "litora", lemma: "lītus", reading: "lī-to-ra", pos: "名词", morphology: ["中性", "复数", "宾格"], gloss: "海岸", role: "方向宾语", relation: "目的地", confidence: 99 },
        ],
      },
      {
        n: "3–4",
        translation: "他在陆地与海洋饱经磨难，缘于天神之力与朱诺难消的愤怒；",
        tokens: [
          { id: "l15", form: "multum", lemma: "multus", reading: "mul-tum", pos: "副词", morphology: ["程度"], gloss: "许多；极其", role: "状语", relation: "修饰 iactatus", confidence: 98 },
          { id: "l16", form: "ille", lemma: "ille", reading: "il-le", pos: "指示代词", morphology: ["阳性", "单数", "主格"], gloss: "那位英雄", role: "主语", relation: "指代埃涅阿斯", confidence: 99 },
          { id: "l17", form: "et", lemma: "et", reading: "et", pos: "连词", morphology: ["并列"], gloss: "和；也", role: "连接", relation: "并列地点", confidence: 99 },
          { id: "l18", form: "terris", lemma: "terra", reading: "ter-ris", pos: "名词", morphology: ["阴性", "复数", "夺格"], gloss: "陆地上", role: "状语", relation: "地点", confidence: 99 },
          { id: "l19", form: "iactatus", lemma: "iactō", reading: "iak-tā-tus", pos: "分词", morphology: ["完成时", "被动", "阳性单数主格"], gloss: "被抛掷，漂泊", role: "谓语分词", relation: "描述主语经历", confidence: 98 },
          { id: "l20", form: "et", lemma: "et", reading: "et", pos: "连词", morphology: ["并列"], gloss: "和", role: "连接", relation: "并列地点", confidence: 99 },
          { id: "l21", form: "alto", lemma: "altum", reading: "al-tō", pos: "名词", morphology: ["中性", "单数", "夺格"], gloss: "深海", role: "状语", relation: "地点", confidence: 97 },
          { id: "l22", form: "vi", lemma: "vīs", reading: "wī", pos: "名词", morphology: ["阴性", "单数", "夺格"], gloss: "力量，暴力", role: "状语", relation: "原因", confidence: 99 },
          { id: "l23", form: "superum", lemma: "superī", reading: "su-pe-rum", pos: "名词", morphology: ["阳性", "复数", "属格"], gloss: "天神们", role: "定语", relation: "修饰 vi", confidence: 97 },
        ],
      },
      {
        n: "5–7",
        translation: "又在战争中历尽苦难，直到建立城市，把神祇带入拉丁姆。",
        tokens: [
          { id: "l24", form: "multa", lemma: "multus", reading: "mul-ta", pos: "形容词", morphology: ["中性", "复数", "宾格"], gloss: "许多事情", role: "宾语", relation: "passus 的宾语", confidence: 99 },
          { id: "l25", form: "quoque", lemma: "quoque", reading: "kwo-kwe", pos: "副词", morphology: ["附加"], gloss: "也", role: "状语", relation: "添加信息", confidence: 99 },
          { id: "l26", form: "et", lemma: "et", reading: "et", pos: "连词", morphology: ["并列"], gloss: "并且", role: "连接", relation: "衔接分句", confidence: 99 },
          { id: "l27", form: "bello", lemma: "bellum", reading: "bel-lō", pos: "名词", morphology: ["中性", "单数", "夺格"], gloss: "战争中", role: "状语", relation: "场景", confidence: 99 },
          { id: "l28", form: "passus", lemma: "patior", reading: "pas-sus", pos: "分词", morphology: ["完成时", "异相", "阳性单数主格"], gloss: "遭受，经历", role: "谓语分词", relation: "描述主语经历", confidence: 97 },
          { id: "l29", form: "dum", lemma: "dum", reading: "dum", pos: "连词", morphology: ["时间"], gloss: "直到", role: "连接", relation: "引导时间从句", confidence: 99 },
          { id: "l30", form: "conderet", lemma: "condō", reading: "kon-de-ret", pos: "动词", morphology: ["未完成过去时", "主动", "虚拟式", "第三人称单数"], gloss: "建立", role: "谓语", relation: "从句核心", confidence: 98 },
          { id: "l31", form: "urbem", lemma: "urbs", reading: "ur-bem", pos: "名词", morphology: ["阴性", "单数", "宾格"], gloss: "城市", role: "宾语", relation: "conderet 的宾语", confidence: 99 },
        ],
      },
    ],
  },
  chinese: {
    id: "chinese",
    language: "文言文",
    shortLanguage: "文言文",
    lang: "zh-Hant",
    direction: "ltr",
    author: "孔子及其弟子",
    title: "論語",
    titleZh: "《论语》",
    edition: "《四书章句集注》本",
    passage: "学而第一 · 1–3 章",
    progress: 18,
    coverMark: "論",
    chapters: [
      { label: "学而第一", detail: "修身与为学", active: true },
      { label: "为政第二", detail: "德政与教化", active: false },
      { label: "八佾第三", detail: "礼乐之本", active: false },
      { label: "里仁第四", detail: "仁德与选择", active: false },
      { label: "公冶长第五", detail: "人物品评", active: false },
      { label: "雍也第六", detail: "中庸与才德", active: false },
    ],
    sections: ["1.1", "1.2", "1.3", "1.4", "1.5", "1.6"],
    lines: [
      {
        n: "1.1",
        translation: "孔子说：“学习之后按时温习，不也是令人喜悦的吗？”",
        tokens: [
          { id: "c1", form: "子", lemma: "子", reading: "zǐ", pos: "名词", morphology: ["尊称", "单数"], gloss: "先生；此处指孔子", role: "主语", relation: "言说者", confidence: 99 },
          { id: "c2", form: "曰", lemma: "曰", reading: "yuē", pos: "动词", morphology: ["言说动词"], gloss: "说", role: "谓语", relation: "引出引语", confidence: 99 },
          { id: "c3", form: "學", lemma: "學", reading: "xué", pos: "动词", morphology: ["及物"], gloss: "学习，求学", role: "谓语", relation: "分句核心", confidence: 97 },
          { id: "c4", form: "而", lemma: "而", reading: "ér", pos: "连词", morphology: ["承接"], gloss: "然后；并且", role: "连接", relation: "连接动作", confidence: 96 },
          { id: "c5", form: "時", lemma: "時", reading: "shí", pos: "副词", morphology: ["时间"], gloss: "按时；时常", role: "状语", relation: "修饰習", confidence: 94 },
          { id: "c6", form: "習", lemma: "習", reading: "xí", pos: "动词", morphology: ["及物"], gloss: "温习，实践", role: "谓语", relation: "承接學", confidence: 98 },
          { id: "c7", form: "之", lemma: "之", reading: "zhī", pos: "代词", morphology: ["第三人称"], gloss: "它；所学内容", role: "宾语", relation: "習的宾语", confidence: 99 },
          { id: "c8", form: "不亦", lemma: "不亦", reading: "bù yì", pos: "固定结构", morphology: ["反问"], gloss: "不也是……吗", role: "语气", relation: "构成反问", confidence: 99 },
          { id: "c9", form: "說", lemma: "說", reading: "yuè", pos: "形容词", morphology: ["通“悦”"], gloss: "喜悦，愉快", role: "谓语", relation: "评价学习", confidence: 98 },
          { id: "c10", form: "乎", lemma: "乎", reading: "hū", pos: "语气词", morphology: ["疑问/反问"], gloss: "吗", role: "语气", relation: "句末反问", confidence: 99 },
        ],
      },
      {
        n: "1.1b",
        translation: "有志同道合的朋友从远方来，不也是令人快乐的吗？",
        tokens: [
          { id: "c11", form: "有朋", lemma: "朋友", reading: "yǒu péng", pos: "名词短语", morphology: ["主语"], gloss: "有志同道合的朋友", role: "主语", relation: "来访者", confidence: 97 },
          { id: "c12", form: "自", lemma: "自", reading: "zì", pos: "介词", morphology: ["处所起点"], gloss: "从", role: "介词", relation: "引导来源", confidence: 99 },
          { id: "c13", form: "遠方", lemma: "遠方", reading: "yuǎn fāng", pos: "名词", morphology: ["处所"], gloss: "远方", role: "介词宾语", relation: "来访来源", confidence: 99 },
          { id: "c14", form: "來", lemma: "來", reading: "lái", pos: "动词", morphology: ["位移动词"], gloss: "到来", role: "谓语", relation: "分句核心", confidence: 99 },
          { id: "c15", form: "不亦", lemma: "不亦", reading: "bù yì", pos: "固定结构", morphology: ["反问"], gloss: "不也是……吗", role: "语气", relation: "构成反问", confidence: 99 },
          { id: "c16", form: "樂", lemma: "樂", reading: "lè", pos: "形容词", morphology: ["状态"], gloss: "快乐", role: "谓语", relation: "评价友人来访", confidence: 98 },
          { id: "c17", form: "乎", lemma: "乎", reading: "hū", pos: "语气词", morphology: ["反问"], gloss: "吗", role: "语气", relation: "句末反问", confidence: 99 },
        ],
      },
      {
        n: "1.1c",
        translation: "别人不了解我，我却不怨恨，不也是君子吗？",
        tokens: [
          { id: "c18", form: "人", lemma: "人", reading: "rén", pos: "名词", morphology: ["泛指"], gloss: "别人", role: "主语", relation: "不知的主体", confidence: 98 },
          { id: "c19", form: "不知", lemma: "知", reading: "bù zhī", pos: "动词短语", morphology: ["否定"], gloss: "不了解（我）", role: "谓语", relation: "分句核心", confidence: 97 },
          { id: "c20", form: "而", lemma: "而", reading: "ér", pos: "连词", morphology: ["转折"], gloss: "却；但是", role: "连接", relation: "连接转折分句", confidence: 96 },
          { id: "c21", form: "不慍", lemma: "慍", reading: "bù yùn", pos: "动词短语", morphology: ["否定", "情态"], gloss: "不恼怒，不怨恨", role: "谓语", relation: "描述君子反应", confidence: 98 },
          { id: "c22", form: "不亦", lemma: "不亦", reading: "bù yì", pos: "固定结构", morphology: ["反问"], gloss: "不也是……吗", role: "语气", relation: "构成反问", confidence: 99 },
          { id: "c23", form: "君子", lemma: "君子", reading: "jūn zǐ", pos: "名词", morphology: ["人格称谓"], gloss: "有德之人", role: "表语", relation: "对主体的判断", confidence: 99 },
          { id: "c24", form: "乎", lemma: "乎", reading: "hū", pos: "语气词", morphology: ["反问"], gloss: "吗", role: "语气", relation: "句末反问", confidence: 99 },
        ],
      },
      {
        n: "1.2",
        translation: "有子说：“孝顺父母、敬爱兄长，却喜欢冒犯上级的人，是很少见的。”",
        tokens: [
          { id: "c25", form: "有子", lemma: "有若", reading: "yǒu zǐ", pos: "专有名词", morphology: ["人名"], gloss: "有若，孔子弟子", role: "主语", relation: "言说者", confidence: 99 },
          { id: "c26", form: "曰", lemma: "曰", reading: "yuē", pos: "动词", morphology: ["言说动词"], gloss: "说", role: "谓语", relation: "引出引语", confidence: 99 },
          { id: "c27", form: "其為人也", lemma: "為人", reading: "qí wéi rén yě", pos: "名词性短语", morphology: ["主题结构"], gloss: "他的为人", role: "主题", relation: "全句话题", confidence: 95 },
          { id: "c28", form: "孝弟", lemma: "孝悌", reading: "xiào tì", pos: "形容词", morphology: ["品德"], gloss: "孝顺父母、敬爱兄长", role: "谓语", relation: "描述为人", confidence: 97 },
          { id: "c29", form: "而", lemma: "而", reading: "ér", pos: "连词", morphology: ["转折"], gloss: "却", role: "连接", relation: "引出反常结果", confidence: 97 },
          { id: "c30", form: "好犯上者", lemma: "犯上", reading: "hào fàn shàng zhě", pos: "名词短语", morphology: ["者字结构"], gloss: "喜好冒犯上级的人", role: "主语", relation: "被判断对象", confidence: 96 },
          { id: "c31", form: "鮮矣", lemma: "鮮", reading: "xiǎn yǐ", pos: "形容词短语", morphology: ["句末语气"], gloss: "很少了", role: "谓语", relation: "判断核心", confidence: 98 },
        ],
      },
    ],
  },
};

export const searchableWorks = [
  { id: "greek", title: "Ἰλιάς", titleZh: "伊利亚特", author: "荷马", language: "古希腊语", meta: "24 卷 · OCT 希腊文版" },
  { id: "latin", title: "Aeneis", titleZh: "埃涅阿斯纪", author: "维吉尔", language: "拉丁语", meta: "12 卷 · 拉丁文校勘本" },
  { id: "chinese", title: "論語", titleZh: "论语", author: "孔子及其弟子", language: "文言文", meta: "20 篇 · 四书章句集注本" },
];
